# -*- coding: utf-8 -*-
"""XLSX_CSV_DB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O2ltxLWONgC27Laoq59zvbZ07kDHZtC6
"""

# ============================================
# 📘 XLSX → CSV → SQLite (.db)

from google.colab import files
import pandas as pd
import sqlite3
import os

# --- Step 1: Upload your Excel file ---
print("📤 Please upload your Excel (.xlsx) file")
uploaded = files.upload()

# Get uploaded filename (e.g., 'data.xlsx')
excel_file = list(uploaded.keys())[0]
base_name = os.path.splitext(excel_file)[0]

# --- Step 2: Convert Excel → CSV ---
csv_file = f"{base_name}.csv"
print(f"📄 Converting {excel_file} → {csv_file} ...")
df = pd.read_excel(excel_file)
df.to_csv(csv_file, index=False)
print(f"✅ Saved CSV as: {csv_file}")

# --- Step 3: Convert CSV → SQLite DB ---
db_file = f"{base_name}.db"
table_name = base_name

print(f"🗃️ Creating SQLite database: {db_file}")
conn = sqlite3.connect(db_file)

# Write DataFrame to SQL table
df.to_sql(table_name, conn, if_exists='replace', index=False)
print(f"✅ Data stored in table '{table_name}' inside {db_file}")

# --- Step 4: Verify sample data ---
preview = pd.read_sql(f"SELECT * FROM {table_name} LIMIT 5;", conn)
print("\n📊 Preview of data from database:")
print(preview)

conn.close()

# --- Step 5: Download generated files ---
print("\n⬇️ Download your generated files:")
files.download(csv_file)
files.download(db_file)

# ============================================
# 📘 MULTI-FILE XLSX → CSV → SQLite (.db)
# Keeps same names for all generated files
# ============================================

from google.colab import files
import pandas as pd
import sqlite3
import os

# --- Step 1: Upload all Excel files ---
print("📤 Please upload one or more Excel (.xlsx) files")
uploaded = files.upload()

# --- Step 2: Loop through each uploaded Excel file ---
for excel_file in uploaded.keys():
    base_name = os.path.splitext(excel_file)[0]
    csv_file = f"{base_name}.csv"
    db_file = f"{base_name}.db"
    table_name = base_name

    print(f"\n📄 Processing {excel_file} ...")

    # --- Convert Excel → CSV ---
    try:
        df = pd.read_excel(excel_file)
        df.to_csv(csv_file, index=False)
        print(f"✅ Converted to {csv_file}")
    except Exception as e:
        print(f"❌ Error reading {excel_file}: {e}")
        continue

    # --- Create SQLite DB and insert data ---
    try:
        conn = sqlite3.connect(db_file)
        df.to_sql(table_name, conn, if_exists='replace', index=False)
        conn.close()
        print(f"🗃️ Created database {db_file} with table '{table_name}'")
    except Exception as e:
        print(f"❌ Error creating DB for {excel_file}: {e}")
        continue

# --- Step 3: Offer downloads for all generated files ---
print("\n⬇️ Download your generated CSV and DB files:")
for excel_file in uploaded.keys():
    base_name = os.path.splitext(excel_file)[0]
    csv_file = f"{base_name}.csv"
    db_file = f"{base_name}.db"
    try:
        files.download(csv_file)
        files.download(db_file)
    except Exception as e:
        print(f"⚠️ Could not auto-download {base_name}: {e}")

print("\n✅ All conversions complete!")

